filmönerileri/filmönerileri/Models/Film.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace filmönerileri.Models
{
    public class Film
    {
        [Key]
        public int Id { get; set; }
        [MaxLength(20, ErrorMessage ="Film adı 100 karakterden daha uzun olamaz.")]
        public string Name { get; set; }
        public int Rating { get; set; }
        public int ReleaseYear { get; set; }
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
        public Category Category{ get; set; }
        [ForeignKey("Category")]
        public int CategoryId { get; set; }
        [DataType(DataType.Upload)]
        public byte[] Image { get; set; }
    }
}

filmönerileri/filmönerileri/Controllers/CommentsController.cs
using filmonerileri.Models;
using filmönerileri.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace filmönerileri.Controllers
{
    public class CommentsController : Controller
    {
        ApplicationDbContext context = new ApplicationDbContext();
        [ChildActionOnly]
        public ActionResult Index([Bind(Prefix ="id")] int FilmId)
        {
            var model = context.Comments.Include("User").Where(c => c.Film.Id == FilmId);
            return PartialView("_Comments", model);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult NewComment(NewCommentViewModel comment, [Bind(Prefix = "id")] int FilmId)
        {
            if (ModelState.IsValid)
            {
                string userId = User.Identity.GetUserId();
                context.Comments.Add(new Comment
                {
                    Body = comment.Body,
                    FilmId = FilmId,
                    UserId = userId
                });
                context.SaveChanges();                
            }
            return RedirectToAction("Details", "Films", new { Id = FilmId });

        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if(context != null)
            {
                context.Dispose();
            }
        }

    }
}

filmönerileri/filmönerileri/Controllers/FilmsController.cs
using filmonerileri.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace filmönerileri.Controllers
{
    public class FilmsController : Controller
    {
        ApplicationDbContext context = new ApplicationDbContext();
        public ActionResult Index(string category)
        {
            var model = context.Films.Where(f => f.Category.Name == category);
            return View(model);
        }

        public ActionResult Details(int id)
        {
            var model = context.Films.Find(id);
            return View(model);
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if(context != null)
            {
                context.Dispose();
            }
        }
    }
}

filmönerileri/filmönerileri/Views/Films/Details.cshtml
@model filmönerileri.Models.Film
@{
    ViewBag.Title = "Details";
}


<div class="col-md-9" style="border:blue 2px">
    <div class="row">
        <div class="col-md-5">

            <img src="~/File?id=@Model.Id" style="width:100%" alt="">
        </div>
        <div class="col-md-7">
            <h4 style="display: inline;">
                @Model.Name (@Model.ReleaseYear)
            </h4>
            <div class="ratings" style="display: inline; padding:0;">
                @for (int i = 0; i < Model.Rating; i++)
                {
                    <span class="glyphicon glyphicon-star"></span>
                }
                @for (int i = 0; i < 5 - Model.Rating; i++)
                {
                    <span class="glyphicon glyphicon-star-empty"></span>
                }
            </div>
            <br /><br />
            <p>@Model.Description</p>
            <br />
        </div>
    </div>
    <br />
    @Html.Action("Index", "Comments")
    @if (Request.IsAuthenticated)
    {
        
        <form action="@Url.Action("NewComment","Comments", new { Model.Id })" method="post">
            @Html.AntiForgeryToken()
            <div class="form-group">
                <label for="Body">Yorumunuz:</label>
                <textarea name="Body" id="Body" class="form-control" placeholder="Bir yorum yazın." style="overflow:auto;" rows="10"></textarea>
            </div>
            <button type="submit" class="btn btn-success">Gönder</button>
        </form>
    }

</div>

filmönerileri/filmönerileri/Views/Films/Index.cshtml
@model IEnumerable<filmönerileri.Models.Film>




<div class="col-md-9">
    @foreach (var item in Model)
    {

        <div class="row">
            <div class="col-sm-4 col-lg-4 col-md-4">
                <div class="thumbnail">

                    <img src="~/File/?id=@item.Id" alt="film image" />
                    <div class="caption">
                        <h4 class="pull-right">@item.ReleaseYear</h4>
                        <h4>
                            <a href="@Url.Action("Details", new { id = item.Id})">@item.Name</a>
                        </h4>
                        <p> @item.Description</p>
                    </div>
                    <div class="ratings">
                        @for (int i = 0; i < item.Rating; i++)
                        {
                            <span class="glyphicon glyphicon-star"></span>
                        }
                        @for (int i = 0; i < 5 - item.Rating; i++)
                        {
                            <span class="glyphicon glyphicon-star-empty"></span>
                        }                       

                    </div>
                </div>
            </div>
        </div>

    }
</div>